### ISSUE TITLE
My alarmsystem goes unavailable from time to time

### ISSUE THREAD

**Issue by robin-vandaele** [uvjustin/alarmdotcom#112]
![Screenshot_20220412-115924_Home Assistant.jpg](https://user-images.githubusercontent.com/7677141/162934702-f16e2a64-b318-4c53-ade4-032a0b94ed59.jpg)
My HA loses connection with alarmdotcom from time to time.

**Comment by elahd** [comment]
Would you mind running this add-in in debug mode for a bit to see if anything interesting comes up in the logs? You can enable debug mode by adding these lines to your configuration.yaml file, followed by rebooting Home Assistant:

```yaml
logger:
  default: info
  logs:
    custom_components.alarmdotcom: debug
```
