### ISSUE TITLE
Arm/Disarm in Homekit

### ISSUE THREAD

**Issue by rbiffle** [uvjustin/alarmdotcom#126]
I cannot seem to get Homekit to Arm/Disarm via Homeassistant.  The alarm.com feature (Installed via HACS) does work in Homeassistant, but I need to enter my PIN code each time.  I've entered my PIN in the GUI, but somehow it's not getting transferred into  Homekit.  Any thoughts?

**Comment by elahd** [comment]
You still need to configure the HomeKit integration via configuration.yaml if you want to use it with an alarm system that has a code. See https://www.home-assistant.io/integrations/homekit/#manual-configuration

```yaml
homekit:
    entity_config:
      alarm_control_panel.home:
        code: 1234
```

The code entered here needs to match the code set in the Alarm.com integration.
