### ISSUE TITLE
status not updated properly and mismatch state of alarm vs web&phone app

### ISSUE THREAD

**Issue by xmmpru83** [uvjustin/alarmdotcom#31]
Hi,

I've installed the plugin, it works ok for arm & disarm the alarm. The problem is that when I set from HASSIO to Arm the alarm, the state is not updated. Within alarm.com the state shows as Disarmed but the alarm itself is having the red led blinking and the arming sound was heard.
The state of disarm is executed properly and its recognized in the web UI.
On the Web it shows [Web] command: arm stay no entry delay silent. But then the icon stills show as disarmed despite being armed at that point in time. Somehow the plugin get to activate the arming but it doesn't shows neither in HASSIO UI or the Alarm.com UI. Like some missing sync between those actions.

any idea ? all the stup is latest version of both homeassistant and the plugin.

**Comment by uvjustin** [comment]
Please post this question on the home assistant community forum under third party integrations. The forum is a better place for tech support questions. Github issues are more for confirmed issues/bugs with the code.

**Comment by xmmpru83** [comment]
I do believe this is a bug... your plugin is sending a weird command to the API of Alarm.com
FYI https://github.com/schwark/pyalarmcom is not making this issue... when it is set to arm, within the app that command have the Arm icon unlike yours.

**Comment by uvjustin** [comment]
Are the options you are arming with exposed in your web portal?
```
#  The three options below are not available on all systems/providers. Check your web portal to see which options are available during arming, and leave the parameter out or set it to "false" if it is not available.

force_bypass:
  description: Specifies when to use the "force bypass" setting when arming. Accepted values are "home", "away", "false" (never), "true" (always).
  required: false
  default: false
  type: string

no_entry_delay:
  description: Specifies when to use the "no entry delay" setting when arming. Accepted values are "home", "away", "false" (never), "true" (always).
  required: false
  default: false
  type: string

silent_arming:
  description: Specifies when to use the "silent arming" setting when arming. Accepted values are "home", "away", "false" (never), "true" (always).
  required: false
  default: false
  type: string
```
