### ISSUE TITLE
Unable to arm with Counterforce

### ISSUE THREAD

**Issue by champdemars** [uvjustin/alarmdotcom#59]
Hello

I am trying to arm my system with your integration but it does not work. However I am perfectly able to disarm, including inside an automation.

Since I don't need to use my code fo arming my system, I did not added it in my configuration. I tried with the code without success.

I am subscribed with Counterforce in Canada. I'm using 2FA.

Here is my configuration.yaml:

```
alarm_control_panel:
  - platform: alarmdotcom
    username: scrambled_user
    password: scrambled_pwd
    # The below parameters are optional
    # code: 1234
    # force_bypass, no_entry_delay, and silent_arming are not supported on all systems/providers. See the description section below.
    force_bypass: "true"
    no_entry_delay: "home"
    silent_arming: "false"
    # two_factor_cookie is only used if your portal is forcing 2FA
    two_factor_cookie: "A0KD871991SSJS..."
```
