### ISSUE TITLE
Error and not loading since upgrade to 0.2

### ISSUE THREAD

**Issue by Somapolice** [uvjustin/alarmdotcom#70]
Logger: homeassistant.config_entries
Source: config_entries.py:344
First occurred: 11:24:28 AM (2 occurrences)
Last logged: 11:25:10 AM

Config entry 'None' for alarmdotcom integration not ready yet; Retrying in background

I use Brinks via Alarm.com. Was working fine with old Config.

**Comment by RB14060** [comment]
Having the same issue on my setup. Component is just stuck in "Retrying setup" status.

**Comment by elahd** [comment]
Thanks for reporting. Try this:

1. Update to the latest beta (v0.2.0-beta.2). (The newest beta spits out more verbose logs.)
2. Add the below to configuration.yaml:
```yaml
logger:
  default: warn
  logs:
    custom_components.alarmdotcom: debug
    pyalarmdotcomajax: debug
```
3. Restart Home Assistant.

If you run into an problem, check the Home Assistant logs for anything relayed to `alarmdotcom` or `pyalarmdotcomajax`.
