### ISSUE TITLE
Configuration required after successful setup

### ISSUE THREAD

**Issue by MithUK1** [uvjustin/alarmdotcom#88]
Ive added the iinstallation, added my alarm.com user and password.  It finds my devices, but then intermttently returns to "your device requires reconfiguration"

I try my username and pasword, and it fails authentication, trying a little later, it passes authentication. 

With 0.1, this never happened.

Happy to test for you if you need feedback

![adt1](https://user-images.githubusercontent.com/60322560/154592078-32f19000-4381-4ac1-84be-b717a3f4253d.jpg)

**Comment by elahd** [comment]
Would you mind running the integration for a few days with debugging enabled? This will provide more detailed logs next time you run into this problem. Add the following to configuration.yaml.

```yaml
logger:
  default: warn
  logs:
    custom_components.alarmdotcom: debug
    pyalarmdotcomajax: debug
```

When the error pops up again, check your Home Assistant logs for details.
