### ISSUE TITLE
Alarm.com Error

### ISSUE THREAD

**Issue by nicocoetzee** [uvjustin/alarmdotcom#91]
Hi - 

I'm getting this error when arming my system via HA:

"Alarm.com Error
Your Alarm.com user does not have permission to armstay your partition. Please log in to Alarm.com to grant the appropriate permissions to your account."

Any ideas on how I can fix it?

Thank you in advance,
n.
![Screen Shot 2022-02-22 at 3 40 15 PM](https://user-images.githubusercontent.com/21128291/155238274-fc04075a-a4ed-4433-926a-9960fd56914a.png)
![Screen Shot 2022-02-22 at 3 41 25 PM](https://user-images.githubusercontent.com/21128291/155238365-fd1b2993-f7b3-41fd-9323-6581cba6f071.png)

**Comment by elahd** [comment]
Would you mind running the integration for a few days with debugging enabled? This will provide more detailed logs next time you run into this problem. Add the following to configuration.yaml.

```yaml
logger:
  default: warn
  logs:
    custom_components.alarmdotcom: debug
    pyalarmdotcomajax: debug
```

When the error pops up again, check your Home Assistant logs for details.
